name: blank
on:
  push:
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check_files 
        uses: BorjaOuterelo/test-file-system-action@v0.0.1
        with:
            path: '/etc'
            files: 'lsb-release'
